# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160127_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default=b'#000000', help_text=b'Hex Value', max_length=7, verbose_name=b'Color'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=model_utils.fields.StatusField(default=b'created', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
